steps:
  # build the container image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ms-infratech-financeiro', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ms-infratech-financeiro']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'ms-infratech-financeiro', '--image', 'gcr.io/$PROJECT_ID/ms-infratech-financeiro', '--region', 'us-central1', '--platform', 'managed', '--quiet']
images:
- gcr.io/$PROJECT_ID/ms-infratech-financeiro

